/**
 * Logging Routes - Query logs from workspace
 *
 * Provides endpoints to access structured console logs
 * Works with Azure Container Apps log capture
 */

const express = require('express');
const router = express.Router();
const { requireAuth, requireAdmin } = require('./authMiddleware');
const { apiLogger } = require('./logger');

/**
 * Get log configuration and status
 * GET /api/logs/status
 */
router.get('/status', requireAuth, (req, res) => {
  try {
    apiLogger.info('📊 Log status requested', { userId: req.user.userId });

    const status = {
      status: 'active',
      logLevel: process.env.LOG_LEVEL || 'INFO',
      categories: ['MAIN', 'API', 'AUTH', 'TWITCH', 'DATABASE'],
      output: 'console (Azure Log Analytics)',
      uptime: process.uptime(),
      memoryUsage: process.memoryUsage(),
      environment: process.env.NODE_ENV || 'development'
    };

    res.json({
      success: true,
      logging: status,
      message: 'Console logging active - check Azure Log Analytics workspace'
    });

  } catch (error) {
    apiLogger.error('Failed to get log status', { error: error.message, userId: req.user.userId });
    res.status(500).json({ error: 'Failed to get log status' });
  }
});

/**
 * Test logging functionality
 * POST /api/logs/test
 */
router.post('/test', requireAuth, (req, res) => {
  try {
    const userId = req.user.userId;
    const testId = Math.random().toString(36).substring(2, 8);

    apiLogger.info(`🧪 Log test initiated by ${req.user.username}`, {
      testId,
      userId,
      timestamp: new Date().toISOString()
    });

    // Test different log levels
    apiLogger.error('Test error log', { testId, level: 'ERROR' });
    apiLogger.warn('Test warning log', { testId, level: 'WARN' });
    apiLogger.info('Test info log', { testId, level: 'INFO' });
    apiLogger.debug('Test debug log', { testId, level: 'DEBUG' });

    // Test specialized logging methods
    apiLogger.auth('test-login', userId, true, { testId });
    apiLogger.twitch('test-event', userId, { testId, eventType: 'follow' });
    apiLogger.database('test-query', 'users', true, 42, { testId });
    apiLogger.performance('test-operation', 1500, { testId });

    res.json({
      success: true,
      testId: testId,
      message: 'Test logs generated successfully',
      logs: [
        'Error level test log',
        'Warning level test log',
        'Info level test log',
        'Debug level test log',
        'Auth event test log',
        'Twitch event test log',
        'Database operation test log',
        'Performance monitoring test log'
      ],
      queryInstructions: 'Use Azure Log Analytics workspace to query these logs with KQL'
    });

  } catch (error) {
    apiLogger.error('Log test failed', { error: error.message, userId: req.user.userId });
    res.status(500).json({ error: 'Log test failed' });
  }
});

/**
 * Get KQL query suggestions for current logs
 * GET /api/logs/queries
 */
router.get('/queries', requireAuth, (req, res) => {
  try {
    const queries = {
      "Find Test Logs": {
        "description": "Find logs generated by the test endpoint",
        "query": `AppTraces
| where TimeGenerated > ago(10m)
| where Message contains "🧪 Log test"
| project TimeGenerated, Message, Properties
| order by TimeGenerated desc`
      },

      "User Activity": {
        "description": "Track specific user's activity in logs",
        "query": `AppTraces
| where TimeGenerated > ago(1h)
| where Properties contains "${req.user.userId}" or Message contains "${req.user.username}"
| project TimeGenerated, Message, SeverityLevel
| order by TimeGenerated desc
| limit 50`
      },

      "Recent Errors": {
        "description": "Find recent error logs",
        "query": `AppTraces
| where TimeGenerated > ago(30m)
| where Message contains "❌" or SeverityLevel >= 3
| project TimeGenerated, Message, Properties
| order by TimeGenerated desc
| limit 20`
      },

      "Performance Issues": {
        "description": "Find slow operations and performance warnings",
        "query": `AppTraces
| where TimeGenerated > ago(1h)
| where Message contains "⏱️" or Message contains "Slow"
| project TimeGenerated, Message, SeverityLevel
| order by TimeGenerated desc`
      }
    };

    apiLogger.info('📋 KQL queries requested', { userId: req.user.userId });

    res.json({
      success: true,
      message: 'KQL queries for Azure Log Analytics workspace',
      userContext: {
        userId: req.user.userId,
        username: req.user.username
      },
      queries: queries,
      instructions: [
        'Copy queries to Azure Log Analytics workspace',
        'Adjust time ranges as needed (ago(1h), ago(30m), etc.)',
        'Add specific search terms with: | where Message contains "search-term"',
        'Use limit N to control number of results'
      ]
    });

  } catch (error) {
    apiLogger.error('Failed to get KQL queries', { error: error.message, userId: req.user.userId });
    res.status(500).json({ error: 'Failed to get queries' });
  }
});

/**
 * Admin endpoint: Get system-wide log statistics
 * GET /api/logs/stats (admin only)
 */
router.get('/stats', requireAuth, requireAdmin, (req, res) => {
  try {
    apiLogger.info('📈 Admin log statistics requested', { userId: req.user.userId });

    const stats = {
      logLevel: process.env.LOG_LEVEL || 'INFO',
      uptime: Math.floor(process.uptime()),
      memoryUsage: process.memoryUsage(),
      cpuUsage: process.cpuUsage(),
      platform: process.platform,
      nodeVersion: process.version,
      environment: process.env.NODE_ENV || 'development',
      logCategories: ['MAIN', 'API', 'AUTH', 'TWITCH', 'DATABASE'],
      outputMethod: 'Console (captured by Azure Log Analytics)'
    };

    res.json({
      success: true,
      statistics: stats,
      message: 'System logging statistics retrieved',
      recommendation: 'Use Azure Log Analytics workspace for detailed log analysis'
    });

  } catch (error) {
    apiLogger.error('Failed to get log statistics', { error: error.message, userId: req.user.userId });
    res.status(500).json({ error: 'Failed to get statistics' });
  }
});

module.exports = router;
